import Header from "@/components/Header";
import { NextAuthProvider } from "@/components/NextAuthProvider";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Learning NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <ReactQueryClientProvider>
          <NextAuthProvider>
            <header className="border-b sticky top-0 z-50 bg-white">
              <Header />
            </header>
            <div className="bg-[#F4F2ED] flex-1 w-full">
              <main>{children}</main>
            </div>
          </NextAuthProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
